language: java
jdk:
- oraclejdk8
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: heroku
  api_key: "60dffffb-8734-4e21-aef0-3db3f0ace717"
  app: startup-hub
